-- 2AM — kompletna šema baze. Pokreni u Supabase → SQL Editor → Run.
-- Bezbjedno je pokrenuti više puta: ništa ne briše, samo dodaje ono što fali.

-- PROIZVODI -------------------------------------------------------------
create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  name        text not null,
  price       integer not null check (price >= 0),  -- u centima (EUR): 2990 = 29,90 €
  category    text not null,                         -- Majice, Duksevi, Kačketi, Komplet
  tag         text,                                  -- npr. 'Novo', 'Bestseller'
  sizes       text[] not null default '{}',
  description text not null default '',
  images      text[] not null default '{}',          -- URL-ovi fotografija
  color       text not null default '#0b0b0d',       -- boja majice (ilustracija kad nema slike)
  ink         text not null default '#f2efe8',       -- boja printa (ilustracija kad nema slike)
  print       text not null default '',              -- tekst printa (ilustracija kad nema slike)
  sort_order  integer not null default 0,
  active      boolean not null default true,         -- false = sakriven iz shopa
  created_at  timestamptz not null default now()
);

-- Popusti: akcijska cijena u centima (prazno = bez popusta), uvijek manja od redovne
alter table public.products add column if not exists sale_price integer;
alter table public.products drop constraint if exists products_sale_price_check;
alter table public.products add constraint products_sale_price_check
  check (sale_price is null or (sale_price > 0 and sale_price < price));

alter table public.products enable row level security;

-- Katalog je javan (samo aktivni proizvodi, samo čitanje)
drop policy if exists "Aktivni proizvodi su javni" on public.products;
create policy "Aktivni proizvodi su javni" on public.products
  for select to anon, authenticated using (active);

grant select on public.products to anon, authenticated;
grant all on public.products to service_role;

-- PORUKE SA KONTAKT FORME -----------------------------------------------
create table if not exists public.contact_messages (
  id         uuid primary key default gen_random_uuid(),
  name       text not null check (char_length(name) <= 100),
  email      text not null check (char_length(email) <= 254),
  message    text not null check (char_length(message) <= 5000),
  created_at timestamptz not null default now()
);

-- Bez polisa: upis samo preko servera (/api/contact); poruke čitaš u Table Editoru
alter table public.contact_messages enable row level security;
revoke all on public.contact_messages from anon, authenticated;
grant all on public.contact_messages to service_role;

-- NARUDŽBE --------------------------------------------------------------
-- Rezervna kopija svake narudžbe (obavještenje stiže emailom preko EmailJS-a)
create table if not exists public.orders (
  id          bigint generated by default as identity primary key,
  reference   text not null unique,              -- npr. 2AM-261008-4F1A9C
  first_name  text not null,
  last_name   text not null,
  email       text not null,
  phone       text not null,
  address     text not null,
  city        text not null,
  items       jsonb not null,                    -- [{ id, name, size, qty, price }]
  subtotal    integer not null,                  -- svi iznosi u centima
  shipping    integer not null,
  total       integer not null,
  created_at  timestamptz not null default now()
);

-- Bez polisa: upis samo preko servera (service role)
alter table public.orders enable row level security;
revoke all on public.orders from anon, authenticated;
grant all on public.orders to service_role;

-- SLIKE PROIZVODA -------------------------------------------------------
-- Javni bucket; upload ide preko servera (jednokratni potpisani link iz /api/admin/uploads)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, '{image/jpeg,image/png,image/webp,image/avif}')
on conflict (id) do nothing;
