-- aam — šema baze. Proizvodi se dodaju kroz /admin.
-- Pokreni u Supabase → SQL Editor. Bezbedno je pokrenuti više puta.

-- PROIZVODI -------------------------------------------------------------
create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  name        text not null,
  price       integer not null check (price >= 0),  -- u centima (EUR): 2990 = 29,90 €
  category    text not null,
  tag         text,                                  -- npr. 'Novo', 'Bestseller'
  sizes       text[] not null default '{}',
  description text not null default '',
  images      text[] not null default '{}',          -- URL-ovi fotografija; prazno = SVG ilustracija
  color       text not null default '#0b0b0d',       -- boja majice (SVG ilustracija)
  ink         text not null default '#f2efe8',       -- boja printa (SVG ilustracija)
  print       text not null default '',              -- tekst printa (SVG ilustracija)
  sort_order  integer not null default 0,
  active      boolean not null default true,         -- false = sakriven iz shopa
  created_at  timestamptz not null default now()
);

alter table public.products enable row level security;

-- Katalog je javan (samo aktivni proizvodi, samo čitanje)
drop policy if exists "Aktivni proizvodi su javni" on public.products;
create policy "Aktivni proizvodi su javni" on public.products
  for select to anon, authenticated using (active);

grant select on public.products to anon, authenticated;
grant all on public.products to service_role;

-- NEWSLETTER ------------------------------------------------------------
create table if not exists public.newsletter_subscribers (
  id         uuid primary key default gen_random_uuid(),
  email      text not null unique check (email = lower(email) and email like '%_@_%._%'),
  created_at timestamptz not null default now()
);

-- Bez polisa: upis i čitanje samo preko servera (service role)
alter table public.newsletter_subscribers enable row level security;
revoke all on public.newsletter_subscribers from anon, authenticated;
grant all on public.newsletter_subscribers to service_role;

-- PORUKE SA KONTAKT FORME ---------------------------------------------
create table if not exists public.contact_messages (
  id         uuid primary key default gen_random_uuid(),
  name       text not null check (char_length(name) <= 100),
  email      text not null check (char_length(email) <= 254),
  message    text not null check (char_length(message) <= 5000),
  created_at timestamptz not null default now()
);

-- Bez polisa: upis preko /api/contact, čitanje u admin panelu (oba preko servera)
alter table public.contact_messages enable row level security;
revoke all on public.contact_messages from anon, authenticated;
grant all on public.contact_messages to service_role;

-- NARUDŽBE -------------------------------------------------------------
-- Rezervna kopija svake narudžbe (glavno obaveštenje stiže emailom preko EmailJS-a)
create table if not exists public.orders (
  id          bigint generated by default as identity primary key,
  reference   text not null unique,              -- npr. 2AM-251007-4F1A9C
  first_name  text not null,
  last_name   text not null,
  email       text not null,
  phone       text not null,
  address     text not null,
  city        text not null,
  items       jsonb not null,                    -- [{ id, name, size, qty, price }]
  subtotal    integer not null,                  -- svi iznosi u centima
  shipping    integer not null,
  total       integer not null,
  created_at  timestamptz not null default now()
);

-- Bez polisa: upis samo preko servera (service role)
alter table public.orders enable row level security;
revoke all on public.orders from anon, authenticated;
grant all on public.orders to service_role;

-- SLIKE PROIZVODA ------------------------------------------------------
-- Javni bucket; upload ide preko servera (jednokratni potpisani link iz /api/admin/uploads)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, '{image/jpeg,image/png,image/webp,image/avif}')
on conflict (id) do nothing;
